package com.project.datasource;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DbInitializer {
    private static final Logger logger = LoggerFactory.getLogger(DbInitializer.class);
    private static final String[] queries = {
            """
		CREATE TABLE IF NOT EXISTS projekt(
		 projekt_id SERIAL, --SERIAL lub INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1)
		 nazwa VARCHAR(50) NOT NULL,
		 opis VARCHAR(1000),
		 dataczas_utworzenia TIMESTAMP DEFAULT now(),
		 data_oddania DATE,
		 CONSTRAINT projekt_pk PRIMARY KEY (projekt_id)
		);
		CREATE TABLE IF NOT EXISTS zadanie (
        zadanie_id SERIAL,
        nazwa VARCHAR(50) NOT NULL,
        opis CLOB,
        kolejnosc INTEGER NOT NULL,
        dataczas_utworzenia TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        status VARCHAR(20),
        data_rozpoczecia DATE,
        data_zakonczenia DATE,
        projekt_id INTEGER NOT NULL,
        CONSTRAINT zadanie_pk PRIMARY KEY (zadanie_id)
          );
		""", 
		"""
		CREATE INDEX IF NOT EXISTS projekt_nazwa_idx ON projekt(nazwa);
		CREATE INDEX IF NOT EXISTS zadanie_nazwa_idx ON zadanie(nazwa);
		ALTER TABLE zadanie ADD CONSTRAINT IF NOT EXISTS zadanie_projekt_fk FOREIGN KEY (projekt_id) REFERENCES projekt (projekt_id) ON DELETE CASCADE;
		ALTER TABLE zadanie ADD CONSTRAINT IF NOT EXISTS unique_kolejnosc UNIQUE (kolejnosc, projekt_id);
		""",
            
    };

    private DbInitializer() {
    }
    
    
    /* Function for ensure that every column exists in the zadanie table */
    /*
    public static void ensureColumnsExist() {
        try (Connection connection = DataSource.getConnection();
             Statement statement = connection.createStatement()) {

            // Check if the columns exist and add them if they don't
            try {
                statement.executeQuery("SELECT status FROM zadanie WHERE 1=0");
            } catch (SQLException e) {
                if (e.getMessage().contains("not found") || e.getMessage().contains("doesn't exist")) {
                    statement.executeUpdate("ALTER TABLE zadanie ADD COLUMN status VARCHAR(20)");
                    System.out.println("Added missing column: status");
                }
            }

            try {
                statement.executeQuery("SELECT data_rozpoczecia FROM zadanie WHERE 1=0");
            } catch (SQLException e) {
                if (e.getMessage().contains("not found") || e.getMessage().contains("doesn't exist")) {
                    statement.executeUpdate("ALTER TABLE zadanie ADD COLUMN data_rozpoczecia DATE");
                    System.out.println("Added missing column: data_rozpoczecia");
                }
            }

            try {
                statement.executeQuery("SELECT data_zakonczenia FROM zadanie WHERE 1=0");
            } catch (SQLException e) {
                if (e.getMessage().contains("not found") || e.getMessage().contains("doesn't exist")) {
                    statement.executeUpdate("ALTER TABLE zadanie ADD COLUMN data_zakonczenia DATE");
                    System.out.println("Added missing column: data_zakonczenia");
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to check and update database schema", e);
        }
    }
    */
    public static void init() {
        try (Connection conection = DataSource.getConnection()) {
            boolean initialAutocommit = conection.getAutoCommit();
            conection.setAutoCommit(false);
            try (Statement stmt = conection.createStatement()) {
                for (int i = 0; i < queries.length; i++) {
                    stmt.executeUpdate(queries[i]);
                    logger.info("QUERY {}:\n{}", i + 1, queries[i]);
                }
                conection.commit();
            } catch (SQLException e) {
                conection.rollback();
                throw new RuntimeException(e);
            } finally {
                if (initialAutocommit)
                    conection.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

}